Fix UID and non-root

diff --git a/docker/1.2/Dockerfile b/docker/1.2/Dockerfile
--- a/docker/1.2/Dockerfile
+++ b/docker/1.2/Dockerfile
@@ -63,4 +63,43 @@ ENV PATH /usr/local/crystal/bin:$PATH
 # 5. TODO: Install development utilities
 
 # ---
-# 6. TODO: Setup non-root user (fixuid)
+# 6. Setup non-root user (fixuid)
+#
+# TODO: detect arch other than x86_64
+RUN --mount=type=cache,target=/var/cache/apk \
+    --mount=type=cache,target=/tmp \
+    set -eux; \
+    # create non-root user & give passwordless sudo
+    { \
+        apk add sudo; \
+        addgroup -g 1000 user; \
+        adduser -u 1000 -G user -h /home/user -s /bin/sh -D user; \
+        mkdir -p /etc/sudoers.d; \
+        echo "user ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/user; \
+        # cleanup backup copies
+        rm /etc/group- /etc/passwd- /etc/shadow-; \
+    }; \
+    # Install fixuid
+    { \
+        cd /tmp; \
+        export FIXUID_VERSION=0.5.1 \
+            FIXUID_SHA256=1077e7af13596e6e3902230d7260290fe21b2ee4fffcea1eb548e5c465a34800; \
+        curl --fail -Lo fixuid.tar.gz https://github.com/boxboat/fixuid/releases/download/v${FIXUID_VERSION}/fixuid-${FIXUID_VERSION}-linux-amd64.tar.gz; \
+        echo "${FIXUID_SHA256} *fixuid.tar.gz" | sha256sum -c - >/dev/null 2>&1; \
+        tar -xf fixuid.tar.gz; \
+        mv ./fixuid /usr/local/bin/; \
+        chmod u+s /usr/local/bin/fixuid; \
+        rm fixuid.tar.gz; \
+    }; \
+    # Generate fixuid config
+    mkdir -p /etc/fixuid; \
+    { \
+        echo "user: user"; \
+        echo "group: user"; \
+    } | tee /etc/fixuid/config.yml
+
+# ---
+# Adjust ENTRYPOINT and current user
+ENTRYPOINT [ "/usr/local/bin/fixuid", "-q" ]
+CMD [ "/bin/sh" ]
+USER user:user
